name: discovery_api_client_generator
version: 0.4.3
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: Create API Client libraries based on the APIs Discovery documentation
homepage: https://github.com/dart-gde/discovery_api_dart_client_generator
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.10.0'
  google_discovery_v1_api: '>=0.4.9'
  logging: '>=0.9.0 <0.10.0'
  meta: '>=0.8.8'
  path: '>=0.9.0 <0.10.0'
dev_dependencies:
  bot_io: '>=0.25.0'
  hop: '>=0.27.1'
  unittest: '>=0.9.0 <0.10.0'
